const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349035301517";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_00_02_07_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjMzLFxuICAgICAgICAxODUsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTYsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNjEsXG4gICAgICAgIDY2LFxuICAgICAgICAyNDksXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTE3LFxuICAgICAgICA1MyxcbiAgICAgICAgMTUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNDksXG4gICAgICAgIDk4LFxuICAgICAgICAxNjMsXG4gICAgICAgIDE5LFxuICAgICAgICAxMjgsXG4gICAgICAgIDEsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTQsXG4gICAgICAgIDU5LFxuICAgICAgICAxNTksXG4gICAgICAgIDY0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDIzLFxuICAgICAgICAxNjQsXG4gICAgICAgIDEwMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNixcbiAgICAgICAgMTY2LFxuICAgICAgICAyOSxcbiAgICAgICAgNjMsXG4gICAgICAgIDQzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTkwLFxuICAgICAgICA4NyxcbiAgICAgICAgNjYsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTUsXG4gICAgICAgIDEyLFxuICAgICAgICAxNjcsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjM4LFxuICAgICAgICAyNDgsXG4gICAgICAgIDcyLFxuICAgICAgICAxNjUsXG4gICAgICAgIDE1LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjI3LFxuICAgICAgICAxMDEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTcyLFxuICAgICAgICAyMzQsXG4gICAgICAgIDg2LFxuICAgICAgICAyMSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxNzksXG4gICAgICAgIDExMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDIzNSxcbiAgICAgICAgNTEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTcsXG4gICAgICAgIDksXG4gICAgICAgIDIzOCxcbiAgICAgICAgODgsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNzYsXG4gICAgICAgIDYzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNDYsXG4gICAgICAgIDM0LFxuICAgICAgICA0NCxcbiAgICAgICAgMjIsXG4gICAgICAgIDU4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDg5LFxuICAgICAgICAyMzAsXG4gICAgICAgIDkzLFxuICAgICAgICAxMzksXG4gICAgICAgIDE1MixcbiAgICAgICAgNzMsXG4gICAgICAgIDU0LFxuICAgICAgICA0MixcbiAgICAgICAgMTkzLFxuICAgICAgICAyMDAsXG4gICAgICAgIDg0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk3LFxuICAgICAgICA4NixcbiAgICAgICAgOTUsXG4gICAgICAgIDg1LFxuICAgICAgICAxNjcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMzgsXG4gICAgICAgIDQ3LFxuICAgICAgICAwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDYyLFxuICAgICAgICAyOCxcbiAgICAgICAgMzIsXG4gICAgICAgIDc5LFxuICAgICAgICAxMDIsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNDksXG4gICAgICAgIDY0LFxuICAgICAgICAxODMsXG4gICAgICAgIDEwMixcbiAgICAgICAgOTMsXG4gICAgICAgIDI4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDQ0LFxuICAgICAgICA3NCxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDkwLFxuICAgICAgICA2MixcbiAgICAgICAgMTIxLFxuICAgICAgICA2LFxuICAgICAgICAxMTNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTQyLFxuICAgICAgICAyMzUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNjIsXG4gICAgICAgIDYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxODcsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxNjgsXG4gICAgICAgIDEsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxOSxcbiAgICAgICAgMTM0LFxuICAgICAgICA4NyxcbiAgICAgICAgMjMzLFxuICAgICAgICAxMDEsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTEyLFxuICAgICAgICAyMjMsXG4gICAgICAgIDczLFxuICAgICAgICAxMTAsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTY1LFxuICAgICAgICAxNzksXG4gICAgICAgIDg3LFxuICAgICAgICA5OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDEsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTAxLFxuICAgICAgICA3NyxcbiAgICAgICAgMjE1LFxuICAgICAgICAxNDksXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTk4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjA2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDc4LFxuICAgICAgICA2NSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMDYsXG4gICAgICAgIDc2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDY4LFxuICAgICAgICAxMDcsXG4gICAgICAgIDMxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTUyLFxuICAgICAgICA3NSxcbiAgICAgICAgNTIsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTA0LFxuICAgICAgICAxNyxcbiAgICAgICAgMTY1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgNzJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgNSxcbiAgICAgICAgICA2MixcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDkzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTQ0LFxuICAgICAgICA2MCxcbiAgICAgICAgODMsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzQsXG4gICAgICAgIDE2MSxcbiAgICAgICAgOSxcbiAgICAgICAgNTksXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxODgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTc4LFxuICAgICAgICAxNTMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNjAsXG4gICAgICAgIDk1LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMzAsXG4gICAgICAgIDExMixcbiAgICAgICAgMjA5LFxuICAgICAgICA0NCxcbiAgICAgICAgNzMsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxODAsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTcyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0OSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTIwLFxuICAgICAgICAxMDIsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDI5LFxuICAgICAgICA5MyxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI2LFxuICAgICAgICA2MCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMzQsXG4gICAgICAgIDI5LFxuICAgICAgICAxMyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxODMsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTU0LFxuICAgICAgICAyMixcbiAgICAgICAgMTY5LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE1MCxcbiAgICAgICAgOSxcbiAgICAgICAgNzAsXG4gICAgICAgIDc1LFxuICAgICAgICAxNDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE2MyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ2b0Q5d0hUUnA2MXNvb0d3c0wyRml6Mmx2V3RJQ29UWHV1V29FWE1hUkdBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJibW5yLV8wRFRjLXBwREV0VTh1cnZRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjFjMTY4YTExLTI4ZTMtNGNkNi1iZDFkLTdhMDQzZmQ5ZjI5NlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMTcsXG4gICAgICAyMjEsXG4gICAgICAxMDQsXG4gICAgICAzNyxcbiAgICAgIDMsXG4gICAgICA1OCxcbiAgICAgIDE4NSxcbiAgICAgIDE5MSxcbiAgICAgIDQ4LFxuICAgICAgMjEyLFxuICAgICAgMjM5LFxuICAgICAgMTA5LFxuICAgICAgMjUyLFxuICAgICAgMTY3LFxuICAgICAgMTMsXG4gICAgICA4OSxcbiAgICAgIDI5LFxuICAgICAgMzcsXG4gICAgICAxOTUsXG4gICAgICAxMzZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTA0LFxuICAgICAgMTY0LFxuICAgICAgNixcbiAgICAgIDEwNCxcbiAgICAgIDE0OSxcbiAgICAgIDczLFxuICAgICAgMTcxLFxuICAgICAgMTAxLFxuICAgICAgMTA2LFxuICAgICAgNzEsXG4gICAgICAyNDcsXG4gICAgICA5MyxcbiAgICAgIDc2LFxuICAgICAgMTg0LFxuICAgICAgMTM0LFxuICAgICAgMTE2LFxuICAgICAgMjM5LFxuICAgICAgMTUxLFxuICAgICAgMTA5LFxuICAgICAgMTA4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIk5OTUJIM1cxXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ5MDM1MzAxNTE3OjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJLaW5ncyBEaWdpdGFsc1wiLFxuICAgIFwibGlkXCI6IFwiMTcxODc2MjAyNjAyNTYxOjNAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTEdtLytVQ0VQVHZuTFFHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJYSC9vRFVSVWh4ZkdUMlU3WGRWV2J2SUZrTG9pZVpKWkZiR3VPV3IvWGlzPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIi9YOGhKRUJiT0dDRDI1NEtiQU0yRW5JT1ZaQTJVUWw5L3VLSCsxaUdKN1FvczBqZklyOXpFY0RQTTlFUkV6M2E4R2dkd0dLR1VhL045b0N5aHRyYUN3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIk95TVVSSEtYYkpiN003UDNYT3NZMFVrUFFlSjA5V2gxUTQ2RUZCSmw2YzJEYUFNcXcwQUU0K0NiVmtVdm9QREp2eTZlUGpaMGZjT3JVVFVvQ2FEd2l3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwMzUzMDE1MTc6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDQzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwMzUzMDE1MTc6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDQzXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjAxMzc3MjAsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFEejJcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUR6Mi5qc29uIjogIntcImtleURhdGFcIjpcIlR0UWdDNTY4ZWFwekR4cmdWMGt1b1FTdmZZdTFXK2V3TzE5akJkL2gvNm89XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NzUwNzY4OTQ1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjAxMzc3MjUzMDBcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
